services:
  mysql:
    image: mysql:8.4
    container_name: dineary-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:8
    container_name: dineary-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

volumes:
  mysql-data:
